---
apiVersion: apps/v1
 
kind: Deployment
 
metadata:
 
  name: eureka-server
 
spec:
 
  selector:

    matchLabels:

      app: spring-boot-app

  replicas: 1
 
  template:
 
    metadata:
 
      labels:
 
        app: spring-boot-app
 
    spec:
 
      containers:
 
        - name: eureka-server-instance
 
          image: registry.cn-hangzhou.aliyuncs.com/magiclian/eureka-server:v3
 
          ports:
 
            - containerPort: 8761
          env:
            - name: EUREKA_URL
              value: eureka-server

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  ports:
  - port: 8761
    targetPort: 8761
    name: http
  selector:
    app: spring-boot-app
  type: NodePort




